version: '3.4'

networks:
  app-network:
    driver: bridge

services:
#  client:
#    image: ${DOCKER_REGISTRY-}client
#    container_name: client.app
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    environment:
#      - REACT_APP_API_URL="http://backend:8080/api"
#    networks:
#      - app-network
#    depends_on:
#      - backend
#    ports:
#      - "3000:3000"

  backend-db:
    image: mysql:latest
    container_name: backend.db
    environment:
      - MYSQL_ROOT_PASSWORD=402986
      - MYSQL_DATABASE=goldengroup
    volumes:
      - ./mysql_bd:/var/lib/mysql
    ports:
      - "33006:3306"
    networks:
      - app-network
    command: --lower-case-table-names=2

  backend:
    image: ${DOCKER_REGISTRY-}backend
    container_name: backend.app
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - backend-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://backend-db:3306/goldengroup
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 402986
    networks:
      - app-network