services:
  eureka-server:
    image: ${DOCKER_REGISTRY-}eureka-server
    container_name: eureka-server
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      -  "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - app-network

  backend-db:
    image: mysql
    container_name: backend-db
    environment:
      - MYSQL_ROOT_PASSWORD=402986
      - MYSQL_DATABASE=goldengroup
    volumes:
      - ./mysql_bd:/var/lib/mysql
    ports:
      - "33006:3306"
    networks:
      - app-network
    command: --lower-case-table-names=2

  backend:
    image: ${DOCKER_REGISTRY-}backend
    container_name: backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://backend-db:3306/goldengroup
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=402986
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - app-network

  authorization-service:
    image: ${DOCKER_REGISTRY-}authorization
    container_name: authorization-app
    build:
      context: ./authorization
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8079:8079"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://backend-db:3306/jwt_authorization
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=402986
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
